// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlcpprW4AokEkqOyim8VpvT5wTJ4OEsD8',
    appId: '1:515477990903:web:5f791725de93e3daf792f2',
    messagingSenderId: '515477990903',
    projectId: 'jumpto-web',
    authDomain: 'jumpto-web.firebaseapp.com',
    storageBucket: 'jumpto-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD5aT3FSaJirsWaaD8ilmuoyE_shk58w8',
    appId: '1:515477990903:android:7ab92e1ed9ca6705f792f2',
    messagingSenderId: '515477990903',
    projectId: 'jumpto-web',
    storageBucket: 'jumpto-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1E-JMfSe53q9Lg4fzm3-AX3YCXd8dVT0',
    appId: '1:515477990903:ios:05dca6122562fd07f792f2',
    messagingSenderId: '515477990903',
    projectId: 'jumpto-web',
    storageBucket: 'jumpto-web.firebasestorage.app',
    iosBundleId: 'com.example.jumpto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1E-JMfSe53q9Lg4fzm3-AX3YCXd8dVT0',
    appId: '1:515477990903:ios:05dca6122562fd07f792f2',
    messagingSenderId: '515477990903',
    projectId: 'jumpto-web',
    storageBucket: 'jumpto-web.firebasestorage.app',
    iosBundleId: 'com.example.jumpto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlcpprW4AokEkqOyim8VpvT5wTJ4OEsD8',
    appId: '1:515477990903:web:86e84a52f1c1cde2f792f2',
    messagingSenderId: '515477990903',
    projectId: 'jumpto-web',
    authDomain: 'jumpto-web.firebaseapp.com',
    storageBucket: 'jumpto-web.firebasestorage.app',
  );
}
